#pragma once

#include "stm32l073xx.h"
#include "stm32l0xx_hal_gpio.h"

#define COPERNICUS_GPIO               GPIOB
#define COPERNICUS_UART               LPUART1
#define COPERNICUS_UART_TX_Pin        GPIO_PIN_10
#define COPERNICUS_UART_RX_Pin        GPIO_PIN_11
#define COPERNICUS_UART_IRQn          LPUART1_IRQn
#define COPERNICUS_GPIO_AF4_UART      GPIO_AF4_LPUART1
#define COPERNICUS_LPUART_IRQHandler  LPUART1_IRQHandler
#define COPERNICUS_GPIO_CLK_ENABLE    __HAL_RCC_GPIOB_CLK_ENABLE
#define COPERNICUS_UART_CLK_ENABLE    __HAL_RCC_LPUART1_CLK_ENABLE
#define COPERNICUS_UART_CLK_DISABLE   __HAL_RCC_LPUART1_CLK_DISABLE
#define COPERNICUS_UART_FORCE_RESET   __HAL_RCC_LPUART1_FORCE_RESET
#define COPERNICUS_UART_RELEASE_RESET __HAL_RCC_LPUART1_RELEASE_RESET

#define ERROR_LD_Pin       GPIO_PIN_5
#define ERROR_LD_GPIO_Port GPIOA

#define HX1_DAC                 DAC1
#define HX1_DAC_CHANNEL         DAC_CHANNEL_1
#define HX1_DAC_TRIGGER         DAC_TRIGGER_T6_TRGO
#define HX1_DAC_ALIGN           DAC_ALIGN_12B_R
#define HX1_DAC_CLK_ENABLE      __HAL_RCC_DAC_CLK_ENABLE
#define HX1_DAC_FORCE_RESET     __HAL_RCC_DAC_FORCE_RESET
#define HX1_DAC_RELEASE_RESET   __HAL_RCC_DAC_RELEASE_RESET
#define HX1_TIMER               TIM6
#define HX1_TIMER_CLK_ENABLE    __HAL_RCC_TIM6_CLK_ENABLE
#define HX1_TIMER_FORCE_RESET   __HAL_RCC_TIM6_FORCE_RESET
#define HX1_TIMER_RELEASE_RESET __HAL_RCC_TIM6_RELEASE_RESET
#define HX1_DMA_INSTANCE        DMA1_Channel2
#define HX1_DMA_IRQn            DMA1_Channel2_3_IRQn
#define HX1_DMA_IRQHandler      DMA1_Channel2_3_IRQHandler
#define HX1_DMA_CLK_ENABLE      __HAL_RCC_DMA1_CLK_ENABLE
#define HX1_GPIO_CLK_ENABLE     __HAL_RCC_GPIOA_CLK_ENABLE
#define HX1_GPIO_PIN            GPIO_PIN_4
#define HX1_GPIO_PORT           GPIOA
