#pragma once

#define COPERNICUS_GPIO                GPIOA
#define COPERNICUS_USART               USART1
#define COPERNICUS_USART_TX_Pin        GPIO_PIN_9
#define COPERNICUS_USART_RX_Pin        GPIO_PIN_10
#define COPERNICUS_USART_IRQn          USART1_IRQn
#define COPERNICUS_GPIO_AF4_USART      GPIO_AF4_USART1
#define COPERNICUS_USART_IRQHandler    USART1_IRQHandler
#define COPERNICUS_GPIO_CLK_ENABLE     __HAL_RCC_GPIOA_CLK_ENABLE
#define COPERNICUS_USART_CLK_ENABLE    __HAL_RCC_USART1_CLK_ENABLE
#define COPERNICUS_USART_FORCE_RESET   __HAL_RCC_USART1_FORCE_RESET
#define COPERNICUS_USART_RELEASE_RESET __HAL_RCC_USART1_RELEASE_RESET

#define ERROR_LD_Pin         GPIO_PIN_5
#define ERROR_LD_GPIO_Port   GPIOA
